function p.__get_is_solid() return true end
function p.__get_tex() return "block_dark_concrete_orange_border" end

function p.__main()
	set_default_block("block_e")
    set_pos(3,8,2, "XAR_SOLID_BORING_LETTER_A")
    set_pos(7,2,2, "XAR_SOLID_BORING_LETTER_A")
    set_pos(8,12,2, "XAR_SOLID_BORING_LETTER_A")
    set_pos(12,6,2, "XAR_SOLID_BORING_LETTER_A")
    set_pos(9,12,2, "XAR_SOLID_BORING_LETTER_E")
    set_pos(6,2,2, "XAR_SOLID_BORING_LETTER_E")
    set_pos(12,5,2, "XAR_SOLID_BORING_LETTER_E")
    set_pos(3,9,2, "XAR_SOLID_BORING_LETTER_E")
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_RED_BORDER", 4,3,4, 4,3,11)
    set_pos(10,10,3, "block_xar_weapons_research_facility_entrance")
    add_bent(10,10,5, "bent_base_ring_green")
    add_bent(7,7,1, "bent_base_ring_pink_dest")
    set_pos(10,4,1, "XAR_SPACE_GALAXY_FLOWER")
    set_pos(10,10,1, "XAR_SPACE_GALAXY_FLOWER")
    set_pos(5,10,1, "XAR_SPACE_GALAXY_FLOWER")
    set_pos(5,4,1, "XAR_SPACE_GALAXY_FLOWER")
    create_rect("XAR_EMPTY_BORING", 7,5,1, 7,9,1)
    create_rect("XAR_EMPTY_BORING", 10,5,5, 10,5,15)
    create_rect("XAR_EMPTY_BORING", 10,5,1, 10,5,2)
    create_rect("XAR_EMPTY_BORING", 14,2,0, 14,2,15)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_WHITE_BORDER", 4,4,4, 4,11,4)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_WHITE_BORDER", 10,3,4, 11,9,4)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_WHITE_BORDER", 10,11,4, 10,11,5)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_WHITE_BORDER", 9,9,5, 9,11,5)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_WHITE_BORDER", 5,3,4, 9,11,4)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_WHITE_BORDER", 10,9,5, 11,9,5)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_WHITE_BORDER", 11,10,4, 11,11,5)
    set_pos(10,2,2, "XAR_SOLID_BORING_LETTER_N")
    set_pos(12,9,2, "XAR_SOLID_BORING_LETTER_N")
    set_pos(5,12,2, "XAR_SOLID_BORING_LETTER_N")
    set_pos(3,5,2, "XAR_SOLID_BORING_LETTER_N")
    set_pos(6,12,2, "XAR_SOLID_BORING_LETTER_O")
    set_pos(3,6,2, "XAR_SOLID_BORING_LETTER_O")
    set_pos(12,8,2, "XAR_SOLID_BORING_LETTER_O")
    set_pos(9,2,2, "XAR_SOLID_BORING_LETTER_O")
    set_pos(3,4,2, "XAR_SOLID_BORING_LETTER_S")
    set_pos(12,10,2, "XAR_SOLID_BORING_LETTER_S")
    create_rect("XAR_GLASS", 4,12,1, 11,12,1)
    create_rect("XAR_GLASS", 4,2,1, 11,2,1)
    create_rect("XAR_GLASS", 12,3,1, 12,11,1)
    create_rect("XAR_GLASS", 3,3,1, 3,11,1)
    set_pos(12,7,2, "XAR_SOLID_BORING_LETTER_P")
    set_pos(3,7,2, "XAR_SOLID_BORING_LETTER_P")
    set_pos(7,12,2, "XAR_SOLID_BORING_LETTER_P")
    set_pos(8,2,2, "XAR_SOLID_BORING_LETTER_P")
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER", 3,3,2, 3,3,3)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER", 6,11,2, 9,11,2)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER", 5,10,2, 5,11,2)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER", 5,2,3, 9,12,3)
    set_pos(3,12,1, "XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER")
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER", 5,3,2, 5,4,2)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER", 10,11,3, 10,12,3)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER", 12,3,2, 12,3,3)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER", 3,2,1, 3,2,3)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER", 11,10,3, 11,12,3)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER", 6,3,2, 10,3,2)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER", 12,2,1, 12,2,3)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER", 12,4,3, 12,11,3)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER", 12,12,1, 12,12,3)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER", 10,2,3, 11,9,3)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER", 10,10,2, 10,11,2)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER", 3,2,0, 12,12,0)
    set_pos(10,4,2, "XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER")
    set_pos(12,11,2, "XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER")
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER", 11,2,2, 11,12,2)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER", 4,2,2, 4,12,3)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER", 3,11,2, 3,12,2)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER", 3,4,3, 3,12,3)
    set_pos(5,2,2, "XAR_SOLID_BORING_LETTER_W")
    set_pos(3,10,2, "XAR_SOLID_BORING_LETTER_W")
    set_pos(12,4,2, "XAR_SOLID_BORING_LETTER_W")
    set_pos(10,12,2, "XAR_SOLID_BORING_LETTER_W")
	
    add_bent(11,7,1, "bent_base_ring_green")
    set_pos(8,7,1, "block_xar_weapons_research_facility_pinksecret")
    set_pos(3,7,1, "XAR_BRISTOL_ONE_WAY_X_NEG")
    set_pos(10,10,4, "XAR_RAIL_CAVE_WHITE_BOX")
    set_pos(10,10,6, "XAR_ANTI_PLUG_GLASS")
	
	add_bent(4,3,13,"bent_base_save")
	
	add_bent_s(8,8,8,"bent_base_txt","This is a great place to get various Nuke and EMP upgrades.\n\nThe only way to leave is via a waypoint. When you shrink, all of your ammo will be taken by a ^xFFFFFFWhite Box Device.^!")

	
end