function p.__get_is_solid() return false end
function p.__get_tex() return "" end

--Note: I left a hint in block_pk_challenge_1 for this part. There is also a hint for Pink-out of ying forest
function p.__main()
    set_default_block("XAR_EMPTY_BORING")
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER", 15,0,12, 15,2,12)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER", 0,13,3, 0,15,15)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER", 15,3,13, 15,3,15)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_ORANGE_BORDER", 0,0,0, 0,12,15)
    create_rect("XAR_GLASS", 15,4,13, 15,15,15)
    create_rect("XAR_GLASS", 15,0,0, 15,15,11)
    create_rect("XAR_GLASS", 15,3,12, 15,15,12)
    ment_start(4,5,8, "ment_key_guard_green")
    ment_set_f("__radius", 1.5)
    ment_set_i("shoot_proj_damage", 0)
    ment_end()
    ment_start(12,4,4, "ment_key_guard_blue")
    ment_set_f("__radius", 1.5)
    ment_set_i("shoot_proj_damage", 0)
    ment_end()
    ment_start(8,11,3, "ment_key_guard_dans_house")
    ment_set_f("__radius", 1.5)
    ment_set_i("shoot_proj_damage", 0)
    ment_end()
    ment_start(13,13,2, "ment_key_guard_laser_genesis")
    ment_set_f("__radius", 1.5)
    ment_set_i("shoot_proj_damage", 0)
    ment_end()
    ment_start(7,12,12, "ment_key_guard_universe")
    ment_set_f("__radius", 1.5)
    ment_set_i("shoot_proj_damage", 0)
    ment_end()
    ment_start(9,3,12, "ment_key_guard_yellow")
    ment_set_f("__radius", 1.5)
    ment_set_i("shoot_proj_damage", 0)
    ment_end()
    add_env_rect( 1,0,0, 14,15,15, "notlordofthekeys")
end
