function p.__get_is_solid() return false end
function p.__get_tex() return "" end

function p.__main()
    set_default_block("XAR_EMPTY_BORING")
    create_rect("XAR_ANTI_PLUG_CHILD", 1,0,0, 15,0,0)
    create_rect("XAR_ANTI_PLUG_CHILD", 0,0,0, 0,15,0)
    create_rect("XAR_ANTI_PLUG_CHILD", 1,15,15, 15,15,15)
    create_rect("XAR_ANTI_PLUG_CHILD", 15,15,1, 15,15,14)
    create_rect("XAR_ANTI_PLUG_CHILD", 0,0,1, 0,0,15)
    create_rect("XAR_ANTI_PLUG_CHILD", 0,15,1, 0,15,14)
    create_rect("XAR_ANTI_PLUG_CHILD", 15,1,0, 15,14,0)
    create_rect("XAR_ANTI_PLUG_CHILD", 1,0,15, 15,0,15)
    create_rect("XAR_ANTI_PLUG_CHILD", 15,1,15, 15,14,15)
    create_rect("XAR_ANTI_PLUG_CHILD", 0,1,15, 0,15,15)
    create_rect("XAR_ANTI_PLUG_CHILD", 15,0,1, 15,0,14)
    create_rect("XAR_ANTI_PLUG_CHILD", 1,15,0, 15,15,0)
    create_rect("XAR_GLASS", 0,1,1, 0,14,14)
    create_rect("XAR_GLASS", 1,1,0, 14,14,0)
    create_rect("XAR_GLASS", 1,1,15, 14,14,15)
    create_rect("XAR_GLASS", 15,1,1, 15,14,14)
    create_rect("XAR_GLASS", 1,15,1, 14,15,14)
    create_rect("XAR_GLASS", 1,0,1, 14,0,14)
    -- two blue rings seperated by a space to test
    add_bent(3,3,3,"bent_base_ring_blue")
    add_bent(3,3,5,"bent_base_ring_blue")
    --a 2x2x2 green ring configuration, proving easily going through.
    add_bent(5,3,3,"bent_base_ring_green")
    add_bent(5,3,4,"bent_base_ring_green")
    add_bent(5,4,3,"bent_base_ring_green")
    add_bent(5,4,4,"bent_base_ring_green")
    add_bent(6,3,3,"bent_base_ring_green")
    add_bent(6,3,4,"bent_base_ring_green")
    add_bent(6,4,3,"bent_base_ring_green")
    add_bent(6,4,4,"bent_base_ring_green")
    --a 2x2x2 red ring configuration, proving not so easily going through.
    add_bent(8,3,3,"bent_base_ring_red")
    add_bent(8,3,4,"bent_base_ring_red")
    add_bent(8,4,3,"bent_base_ring_red")
    add_bent(8,4,4,"bent_base_ring_red")
    add_bent(9,3,3,"bent_base_ring_red")
    add_bent(9,3,4,"bent_base_ring_red")
    add_bent(9,4,3,"bent_base_ring_red")
    add_bent(9,4,4,"bent_base_ring_red")
    add_bent(9,9,9,"bent_base_txt","Yeah this isn't finished... cause clearly the Ring interaction isn't working as expected. They all seem to be using a variable named ^xFFFFFFdist^! which is based of absolute distance from bent, so they aren't like cubes. \nI think a better way of doing this would be getting a distance in each of the three axes to see if the player is within the cube shaped hitbox of the ring instead of a sphere shaped hitbox, which is what the current system does. \n\nSo yeah, Dan pls fix this ^xFF00FFbug^! and then I can ^x00FF00maybe^! finish this.")
end
