function p.__get_is_solid() return true end
function p.__get_tex() return "block_dark_concrete_red_border" end

function p.__main()
    set_default_block("block_e")
	add_bent_s(4,7,5,"bent_base_txt","This is a Rail Showdown Rift.\n\nThere are many Railgun Firerate and Damage upgrades in the end, as well as plentiful ammo.\n\n^x0000ffYou will need to fight through 5 5x5x5 mazes.^!")
    set_pos(6,8,6, "XAR_SOLID_BORING_EXPANDER")
    set_pos(6,6,6, "XAR_SOLID_BORING_EXPANDER")
    set_pos(8,8,6, "XAR_SOLID_BORING_EXPANDER")
    set_pos(8,6,6, "XAR_SOLID_BORING_EXPANDER")
    set_pos(6,8,7, "XAR_ASCEND_SIMPLE")
    set_pos(6,6,7, "XAR_ASCEND_SIMPLE")
    set_pos(8,8,7, "XAR_ASCEND_SIMPLE")
    set_pos(8,6,7, "XAR_ASCEND_SIMPLE")
    set_pos(7,8,7, "XAR_ASCEND_SIMPLE_2")
    set_pos(8,7,7, "XAR_ASCEND_SIMPLE_2")
    set_pos(7,6,7, "XAR_ASCEND_SIMPLE_2")
    set_pos(6,7,7, "XAR_ASCEND_SIMPLE_2")
    set_pos(7,7,7, "XAR_DESCEND_SIMPLE")
    create_rect("block_xar_rail_showdown_maze_2", 7,7,3, 7,7,4)
    create_rect("block_xar_rail_showdown_maze", 7,7,5, 7,7,6)
    set_pos(7,7,2, "block_xar_rail_showdown_maze_3")
    set_pos(7,6,6, "XAR_SOLID_BORING_DARK_CONCRETE_RED_BORDER")
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_RED_BORDER", 6,6,1, 6,8,5)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_RED_BORDER", 7,8,1, 7,8,6)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_RED_BORDER", 6,6,0, 8,8,0)
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_RED_BORDER", 8,7,1, 8,8,5)
    set_pos(6,7,6, "XAR_SOLID_BORING_DARK_CONCRETE_RED_BORDER")
    set_pos(8,7,6, "XAR_SOLID_BORING_DARK_CONCRETE_RED_BORDER")
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_RED_BORDER", 7,6,1, 8,6,5)
	add_bent(7,7,7, "bent_base_ring_green")
    create_rect("XAR_SOLID_BORING_DARK_CONCRETE_RED_BORDER", 4,7,0, 4,7,2)
    add_bent(4,7,3, "bent_base_ring_pink_dest")
    set_pos(7,7,1, "block_xar_rail_showdown_maze_vault")
end